name: Run tests
on: push

jobs:
  run-linter-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: Check prettier
        run: pnpm run check-prettier

      - name: Check types
        run: pnpm run check-types

      - name: Lint code
        run: pnpm run check-eslint

      - name: Run tests
        run: pnpm test
